// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTCEW8LW1JcF38sbcThiKx86HwgU6QYw',
    appId: '1:120223259659:web:e43e850ac58175967b3b0e',
    messagingSenderId: '120223259659',
    projectId: 'petdoor-a716a',
    authDomain: 'petdoor-a716a.firebaseapp.com',
    storageBucket: 'petdoor-a716a.appspot.com',
    measurementId: 'G-7RBQR2C3FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD24gb7Af53E-YoGWR61BjqCHbZMMFXkxU',
    appId: '1:120223259659:android:6b059c66c12589977b3b0e',
    messagingSenderId: '120223259659',
    projectId: 'petdoor-a716a',
    storageBucket: 'petdoor-a716a.appspot.com',
  );

}